import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { Profile, Job } from '@/types';

// Register fonts
Font.register({
  family: 'Inter',
  src: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap',
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Inter',
    backgroundColor: '#FFFFFF',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#6366F1',
    paddingBottom: 15,
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0A0F1E',
    marginBottom: 5,
  },
  contactInfo: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 3,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0A0F1E',
    marginBottom: 10,
    marginTop: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 5,
  },
  text: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 5,
  },
  jobRole: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6366F1',
    marginBottom: 3,
  },
  company: {
    fontSize: 11,
    color: '#0A0F1E',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  footer: {
    fontSize: 9,
    color: '#9CA3AF',
    marginTop: 30,
    textAlign: 'center',
  },
  badge: {
    fontSize: 9,
    backgroundColor: '#EEF2FF',
    color: '#4338CA',
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginRight: 5,
    marginBottom: 5,
  },
});

interface CVGeneratorProps {
  profile: Profile;
  job: Job;
}

export function CVGenerator({ profile, job }: CVGeneratorProps) {
  const skills = [
    'Full Stack Development',
    'React & Next.js',
    'TypeScript',
    'Node.js',
    'PostgreSQL',
    'AWS & Cloud Architecture',
    'System Design',
    'Agile & Scrum',
  ];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{profile.full_name}</Text>
          <Text style={styles.contactInfo}>{profile.email}</Text>
          <Text style={styles.contactInfo}>{profile.location}</Text>
        </View>

        {/* Target Role */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Target Role</Text>
          <Text style={styles.jobRole}>{job.role}</Text>
          <Text style={styles.company}>{job.company}</Text>
          <Text style={styles.text}>{job.location}</Text>
        </View>

        {/* Professional Summary */}
        {profile.profile_summary && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Professional Summary</Text>
            <Text style={styles.text}>{profile.profile_summary}</Text>
          </View>
        )}

        {/* Skills */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Core Skills</Text>
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {skills.map((skill, idx) => (
              <View key={idx} style={styles.badge}>
                <Text>{skill}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Experience Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Professional Experience</Text>
          <Text style={styles.company}>Senior Software Engineer</Text>
          <Text style={styles.text}>Tech Company Inc. | 2021 - Present</Text>
          <Text style={styles.text}>
            • Led development of full-stack applications using React and Node.js
          </Text>
          <Text style={styles.text}>
            • Architected scalable microservices infrastructure on AWS
          </Text>
          <Text style={styles.text}>
            • Mentored junior developers and conducted code reviews
          </Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by CareerAI for {job.company} | {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
